/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.jiayu.kafkakt

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun appHasAGreeting() {
        assertEquals(1, 1)
    }
}
